name: deploy-website
run-name: Website deploy
on: [push]
jobs:
    build-doco:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "14"
            # Build
            - run: cd apps/docs-website
            - run: npm build
            - run: ls
